### ISSUE TITLE
Refactor UploadOptions

### ISSUE THREAD

**Issue by Lurk** [Lurk/cloudinary_rs#14]
Looking back, the structure of https://github.com/Lurk/cloudinary_rs/blob/main/src/upload/mod.rs#L24 was a mistake.

Preferably, we should have something similar to Transformations https://github.com/Lurk/cloudinary_rs/blob/main/src/transformation/mod.rs#L18

**Comment by McEazy2700** [comment]
Hmmm, is there anything in particular that you'll like to change, cause I lookded at both of them and they seem similarly structured. To me at least.

**Comment by Lurk** [comment]
I am still trying to figure out how I see it. What I do not like is the unhealthy amount getters and setters in UploadOptions.

**Comment by McEazy2700** [comment]
Really? I actually thought it was a good design. I think the getters and setters make it more intuitive. But for `UploadOptions`, do we really need getters, since we're only setting options for upload?

**Comment by McEazy2700** [comment]
But we probably do, I'm sure someone will find a use case for them

**Comment by McEazy2700** [comment]
This is silly, I straight up used the `get_resource_type` method in my commit. My bad 😅
