### ISSUE TITLE
Create a delete asset functionality

### ISSUE THREAD

**Issue by DhvaniBhesaniya** [Lurk/cloudinary_rs#35]
can you create a delete funcnality also , just like this node example,

"
  const publicId = user.profileImg.split('/').pop().split('.')[0];
   await cloudinary.uploader.destroy(publicId);
"

by giving the public id  in the destory method  the assets are being deleted .

can you create a delete method also .

**Comment by Lurk** [comment]
Hey @DhvaniBhesaniya check out 0.5.2 version  
https://github.com/Lurk/cloudinary_rs?tab=readme-ov-file#destroy-an-asset-by-publicid

**Comment by DhvaniBhesaniya** [comment]
Thanks , its working fine
